#!//bin/bash
# dmenu_pass
#  Use dmenu to select a pass password to copy into xclip.

# colors
IFS=':' read nb nf sb sf <<< "black:green:dark green:white"

# the password directory
pdir=${PASSWORD_STORE_DIR:-~/.password-store}
pdir="${pdir%/}/"

# get list of files then strip the path and extension
files=$(find "$pdir" -name *.gpg -type f | sed "s#\.gpg##; s#$pdir##")

# call dmenu to select entry
pick=$(dmenu -i -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -l 10 <<< "${files[@]}")
pick=${pick%%$pdir}
if [[ -z "$pick" ]]; then
    echo "No entry selected." >&2
    exit 1;
fi

# lookup password onto clipboard
if pass show -c "$pick"; then
    printf "Copied pass entry %s.\n" "$pick" >&2
else
    printf "Problem getting pass entry %s.\n" "$pick" >&2
    exit 1
fi
