#!/bin/bash
# dmenu_exec
#  Use dmenu to launch executables.

# colors
IFS=':' read nb nf sb sf <<< "black:white:white:black"

# setup a cache file for names of executables on the path
cache="$HOME/.cache/dmenu_exec";
mkdir -p "${cache%/*}"

# check if cache is missing or expired
if [ ! -e "$cache" ] || [[ $(($(date +%s) - $(date +%s -r "$cache"))) -gt 3600 ]]; then
    # populate cache and list
    IFS=: list=$(find $PATH -not -type d -perm /+x -exec basename {} \; | sort | tee "$cache")
else
    # load list from cache
    list=$(cat "$cache")
fi

# select an executable with dmenu
command=$(dmenu -p "RUN" -i -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" <<< "$list")

# print the command 
echo "$command"

# then run it in the background
exec $command &
